apiVersion: v1
kind: Pod
metadata:
  name: local-proxy
spec:
  serviceAccountName: kubectl-proxy
  containers:
    - name: curl
      image: alpine:3.14
      command: ["sleep", "infinity"]
    - name: kubectl-proxy
      image: carezkh/kubectl-proxy:v0.1.0
      args: ["--wide", "local"]
